### ISSUE TITLE
无法更新天气情况、空气质量、自然灾害预警、各种生活指数以及灾害预警

### ISSUE THREAD

**Issue by zhyf0610** [c1pher-cn/heweather#25]
2024-11-03 13:19:33.846 INFO (MainThread) [homeassistant.components.sensor] Setting up heweather.sensor
2024-11-03 13:19:33.846 INFO (MainThread) [custom_components.heweather.sensor] setup platform sensor.Heweather...
2024-11-03 13:19:33.846 INFO (MainThread) [custom_components.heweather.sensor] Update from JingdongWangxiang's OpenAPI...
2024-11-03 13:19:33.847 INFO (MainThread) [homeassistant.components.sensor] Setting up heweather_hourlyforecast.sensor
2024-11-03 13:19:33.847 INFO (MainThread) [custom_components.heweather_hourlyforecast.sensor] setup platform sensor.Heweather...
2024-11-03 13:19:33.847 INFO (MainThread) [custom_components.heweather_hourlyforecast.sensor] Update from JingdongWangxiang's OpenAPI...
2024-11-03 13:19:33.847 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up heweather_hourlyforecast platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/heweather_hourlyforecast/sensor.py", line 84, in async_setup_platform
    await data.async_update(dt_util.now())
  File "/config/custom_components/heweather_hourlyforecast/sensor.py", line 309, in async_update
    with async_timeout.timeout(15):
TypeError: 'Timeout' object does not support the context manager protocol

2024-11-03 13:19:34.464 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up heweather platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/heweather/sensor.py", line 128, in async_setup_platform
    await suggestion_data.async_update(dt_util.now())
  File "/config/custom_components/heweather/sensor.py", line 641, in async_update
    with async_timeout.timeout(15):
TypeError: 'Timeout' object does not support the context manager protocol

这个应该是async库的共性问题

**Comment by c1pher-cn** [comment]
按报错是接口调用超时，你是说异步调用有问题？我觉得应该是和风的问题正常情况下 下个小时应该就好了

zhyf0610 ***@***.***> 于2024年11月3日周日 15:04写道：

**Comment by zhyf0610** [comment]
我这边一直不更新

**Comment by zhyf0610** [comment]
天气实体是正常更新的

**Comment by zhyf0610** [comment]
TypeError: 'Timeout' object does not support the context manager protocol
这一条感觉不是超时，字面意思感觉是类型不匹配

**Comment by zhyf0610** [comment]
好吧，现在确实恢复了，确实是信息源的问题
